= LPN Central Yocto BSP

This is the Li-Pro.Net Central Yocto BSP Manifest.

== Quick Start

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl https://raw.githubusercontent.com/lipro-yocto/git-repo/lpn-launcher/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

For *version 2.0*, the SHA-1 checksum for `repo` is *1b4bc3c1093cd47bc9d24528cc05833e1296ae45*

=== Freescale Community Yocto BSP

[WARNING]
.Derived Work
This BSP is a special fork of the official Freescale Community Yocto BSP. +
Use the https://github.com/lipro-yocto/lpn-central-bsp-platform/issues[issue tracker on GitHub].
Do not ask on any mailing list.

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir lpn-central-bsp
$: cd lpn-central-bsp
$: repo init -u https://github.com/lipro-yocto/lpn-central-bsp-platform \
             -b fido -m fsl-community.xml
$: repo sync

At the end of the commands you have every metadata you need to start work with.

=== Yocto Core Components

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir lpn-central-bsp
$: cd lpn-central-bsp
$: repo init -u https://github.com/lipro-yocto/lpn-central-bsp-platform \
             -b fido -m default.xml
$: repo sync

At the end of the commands you have every metadata you need to start work with.

=== Build Stage

To start a simple image build:

[source,console]
$: source ./setup-environment build
$: bitbake core-image-minimal

You can use any directory to host your build.

The source code is checked out at `lpn-central-bsp/sources`.

== Contributing

To contribute to the manifest you should send a pull request to this GitHub
project or send the patches for review to the authors mailing address.

Issue tracker::
    https://github.com/lipro-yocto/lpn-central-bsp-platform/issues

Pull requests::
    https://github.com/lipro-yocto/lpn-central-bsp-platform/pulls

Source code::
    https://github.com/lipro-yocto/lpn-central-bsp-platform

When creating patches, please use something like:

[source,console]
$: git format-patch -s --subject-prefix='lpn-central-bsp-platform][PATCH' origin

When sending patches, please use something like:

[source,console]
$: git send-email --to rexut@users.noreply.github.com <generated patch>

== Using Development and Testing Branches

Replace the `repo init` command above with one of the following:

master:: For developers
+
[source,console]
$: repo init -u https://github.com/lipro-yocto/lpn-central-bsp-platform -b master

master-next:: For intrepid developers and testers
+
Patches are typically merged into master-next and then are merged into master
after a testing and comment period. It's possible that master-next has
something you want or need. But it's also possible that using master-next
breaks something that was working before. Use with caution.

[source,console]
$: repo init -u https://github.com/lipro-yocto/lpn-central-bsp-platform -b master-next
